job('Java-maven-Project-Via-DSL') {

   description("Maven job generated by the DSL on ${new Date()}, the project is hosted on github")
   scm{
       ("https://github.com/sramkatiya/jenkin-maven-project.git", 'master')
      }
   triggers{
        scm('* * * * *')   
           }
   steps{
        maven('clean package', 'pom.xml')
        }
   publishers{
         archiveArtifacts '**/*.jar'
             }
}